"""
traffic_logic.py
----------------
The single source of truth for the traffic-control algorithm. The live
backend (app.py), the simulated benchmark (simulation.py) and the value
the dashboard displays as "recommended green" all call the functions in
this module - there is deliberately no second implementation anywhere.

THE ALGORITHM
=============
Lane selection is FIXED ROUND ROBIN:

    Lane 1 -> Lane 2 -> Lane 3 -> Lane 4 -> Lane 1 ...
    North  -> East   -> South  -> West   -> North ...

Vehicle count does NOT decide which lane goes next. It only decides how
long the green lasts:

    green_seconds = 10 + 0.5 * vehicle_count      capped at 60

Consequences that are intentional, not bugs:
  * a lane with zero vehicles still gets its 10-second turn, so no lane
    can be starved by a permanently busy neighbour;
  * counts above 100 all produce the same 60-second cap.

Every green is separated from the next by an ALL-RED clearance interval
(constants.ALL_RED_SEC). All-red is a genuine hardware state ("RRRR");
there is no amber/yellow anywhere in this system because the firmware has
no amber LED and no amber character in its protocol.
"""
from __future__ import annotations

from typing import Dict, Iterable, List, Mapping, Optional

from constants import (
    ALL_RED_STRING,
    BASE_GREEN_SEC,
    LANES,
    MAX_COUNT,
    MAX_GREEN_SEC,
    PER_VEHICLE_SEC,
    SIGNAL_GREEN,
    SIGNAL_RED,
    lane_label,
)


def coerce_count(value: object) -> int:
    """Turn anything a caller might hand us into a sane vehicle count.

    Accepts ints, floats, numeric strings and None. Negative values clamp
    to 0, fractional values truncate, absurd values clamp to MAX_COUNT and
    anything non-numeric becomes 0. Every entry point into the system
    (HTTP body, vision worker, simulation) funnels through this, so no
    other module needs its own validation.
    """
    if value is None or isinstance(value, bool):
        return 0
    try:
        number = float(value)
    except (TypeError, ValueError):
        return 0
    if number != number or number in (float("inf"), float("-inf")):  # NaN / inf
        return 0
    number = int(number)  # truncates toward zero
    return max(0, min(MAX_COUNT, number))


def green_time(vehicle_count: object) -> float:
    """Green duration in seconds for a lane holding `vehicle_count`.

        10 + 0.5 * count, capped at 60

    Returns a float because 0.5 * an odd count is a half second; the phase
    timer is deadline-based so fractional seconds are honoured exactly.
    """
    count = coerce_count(vehicle_count)
    return min(MAX_GREEN_SEC, BASE_GREEN_SEC + PER_VEHICLE_SEC * count)


def green_time_display(vehicle_count: object) -> float:
    """Same value, rounded to one decimal for display purposes only."""
    return round(green_time(vehicle_count), 1)


def next_lane(current: Optional[str], lanes: Iterable[str] = LANES) -> str:
    """Round robin. An unknown or absent current lane starts the cycle."""
    order = list(lanes)
    if current not in order:
        return order[0]
    return order[(order.index(current) + 1) % len(order)]


def signal_string(active_lane: Optional[str], lanes: Iterable[str] = LANES) -> str:
    """Build the wire string, e.g. 'GRRR'. None means all-red."""
    order = list(lanes)
    if active_lane is None:
        return SIGNAL_RED * len(order)
    if active_lane not in order:
        raise ValueError(f"unknown lane {active_lane!r}; known lanes: {order}")
    return "".join(SIGNAL_GREEN if lane == active_lane else SIGNAL_RED for lane in order)


def all_red_string() -> str:
    return ALL_RED_STRING


def signal_for_lane(lane: str, active_lane: Optional[str]) -> str:
    """Per-lane R/G character, derived from the active lane so the
    dashboard can never show a lane state that disagrees with the string
    that was actually sent to the hardware."""
    return SIGNAL_GREEN if (active_lane is not None and lane == active_lane) else SIGNAL_RED


def plan_next_green(current_lane: Optional[str],
                    counts: Mapping[str, object],
                    lanes: Iterable[str] = LANES) -> dict:
    """Decide the next green phase. Used by BOTH the live controller and
    the simulation, which is what keeps them in agreement.

    Returns a dict describing the phase, including a human-readable
    `reason` string that the dashboard shows verbatim - so the explanation
    on screen is generated by the same code that made the decision.
    """
    order = list(lanes)
    lane = next_lane(current_lane, order)
    count = coerce_count(counts.get(lane, 0))
    duration = green_time(count)
    capped = duration >= MAX_GREEN_SEC and BASE_GREEN_SEC + PER_VEHICLE_SEC * count > MAX_GREEN_SEC

    reason = (f"Round robin -> {lane_label(lane)} ({lane}). "
              f"{count} vehicle{'' if count == 1 else 's'} -> "
              f"{BASE_GREEN_SEC:.0f} + {PER_VEHICLE_SEC} x {count} = "
              f"{BASE_GREEN_SEC + PER_VEHICLE_SEC * count:.1f}s"
              + (f", capped at {MAX_GREEN_SEC:.0f}s" if capped else ""))

    return {
        "lane": lane,
        "count": count,
        "green_sec": round(duration, 1),
        "signal": signal_string(lane, order),
        "capped": capped,
        "rule": "round_robin + 10 + 0.5*count (max 60)",
        "reason": reason,
        "next_lane": next_lane(lane, order),
    }


def green_recommendations(counts: Mapping[str, object],
                          lanes: Iterable[str] = LANES) -> Dict[str, float]:
    """What each lane would receive if it went green right now."""
    return {lane: green_time_display(counts.get(lane, 0)) for lane in lanes}
